### ISSUE TITLE
"decoy_set/***.txt" files

### ISSUE THREAD

**Issue by ArcaneEmergence** [jproney/AF2Rank#1]
Dear James and Sergey,

Your work is really interesting and enables accurate structure prediction without MSAs. This will be very useful for my project.

From this line on in file `test_templates.py` [l187](https://github.com/jproney/AF2Rank/blob/d7c9ec1fda03604b95f05132a9c2b4b2739a77a5/test_templates.py#L187) five txt files are read in. Similarly for the casp prediction a file called `gdt_ref_all.txt` is read in. Could you please share these files and potentially other necessary files to run the script that I've missed? 

Thank you in advance!

**Comment by jproney** [comment]
The recent code update has a Google Drive link to all of the relevant `.txt.` files. Thanks!
