### ISSUE TITLE
Runs on Multimeric Structures 

### ISSUE THREAD

**Issue by LivC93** [jproney/AF2Rank#2]
First of all thank you for making this repo available. 

I was wondering if you tested the algorithm on multimeric structures (having more than chain in the PDB file/Structure) or if you have any intuition regarding this possibility.  

Best.
Liv

**Comment by sokrypton** [comment]
Take a look here:
https://colab.research.google.com/github/sokrypton/ColabDesign/blob/main/af/examples/AF2Rank.ipynb

We got an implementation that works on both monomer and multimer.

**Comment by LivC93** [comment]
@sokrypton thank you for pointing me to the colab. I am currently bench-marking a few scoring methods for multimers. So far the average inference time for a trimeric hetero-oligomer is 50sec for AF2Rank.
