### ISSUE TITLE
Args to reproduce main functionality?

### ISSUE THREAD

**Issue by HWaymentSteele** [jproney/AF2Rank#3]
Hi, just wanted to double check if I'm using the right args to use the `test_templates.py` script to reproduce the ranking method that's described in the paper -- should I be using

`--seq_replacement - --add_sidechains_mask_cb` ?

Might be helpful to give an example call in the README, since if I understand right these aren't the default? Thanks!

**Comment by jproney** [comment]
Yes, that's the correct usage. Thanks for pointing this out -- I'll add an example to the README.
