### ISSUE TITLE
Colab notebook: Template used in ranking structures and Runs on multimers

### ISSUE THREAD

**Issue by Chengeng-Yang** [jproney/AF2Rank#4]
Hi there,

Thanks a lot for making this repo available.

I just wanted to ask two questions I have when I tested the colab notebook. 

1) Could you tell me is there a template taken when ranking decoy structures (e.g. the native structure)? I was a little bit confused when reading the set up code. Did the NATIVE PATH in the following cell indicate the template to be used?
![image](https://user-images.githubusercontent.com/101165738/235991439-bea5f676-00f2-47de-bd9b-d8c6e7c0a862.png)

2) When running multimers, even if I have changed model_mode into alphafold-multimer in the settings cell, I still got the following error: "ValueError: Only single model PDBs are supported. Found 0 models.". I also attached a screenshot below. Could you tell me if it's because the chain name only allows a string of length = 1?
![image](https://user-images.githubusercontent.com/101165738/235992872-8bc13b99-078d-44f0-bfc3-55ef40cb14b1.png)

**Comment by sokrypton** [comment]
1. We need something to initialize the model (and later to compute the TMscore against). Later the native structure within the model is replaced by the decoys.
2. CHAIN = "A,B"

**Comment by Chengeng-Yang** [comment]
Many thanks for your reply! I just have a few more concerns.
> 1. We need something to initialize the model (and later to compute the TMscore against). Later the native structure within the model is replaced by the decoys.

Thanks for the reply. I see, so that cell was for the initialization. I was just curious about which template it takes for prediction and ranking (but maybe it's concerned with MSA taken by alphafold, instead of AF2Rank)

> 2. CHAIN = "A,B"
Thanks for the hint, now the model was successfully initialized. But when I run af.predict, I got another error called "ValueError: 'model_1_multimer_v2' is not in list". Could you tell me if there's a way to fix this, like adding an additional parameter in af.predict()?
![image](https://user-images.githubusercontent.com/101165738/236011193-8f3764fb-f11f-4f82-9bdf-04a6091c3743.png)

Thanks for reading the message!

**Comment by sokrypton** [comment]
looks like multimer model got updated to v3. I've updated the notebook. Can you try again.

**Comment by Chengeng-Yang** [comment]
Yes, that works now! Many thanks for your kind help
